---

environment:
  run: python environment/training.py
  name: BoxingDeterministic-v4
  max_episodes: 10000
  infinite_run: True

relaax-parameter-server:
  --bind: localhost:7000
  --metrics-dir: logs/metrics
  --checkpoint-dir: logs/checkpoints
  --log-level: INFO

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: INFO

algorithm:
  name: da3c

  input:
    shape: [84, 84]
    history: 4
    use_convolutions: true

  output:
    continuous: false
    action_size: 18               # action size for the given environment

  batch_size: 5                   # local loop size for one episode

  gpu: false                      # to use GPU, set to the True
  lstm: true                      # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  learning_rate: 7e-4
  entropy_beta: 1e-2              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor
  RMSProp:
    decay: 0.99
    epsilon: 0.1
    gradient_norm_clipping: 40
